### ISSUE TITLE
Can I use your code ?

### ISSUE THREAD

**Issue by gmatesunny** [bowbowbow/DecisionTree#1]
I wanted to use your code with some modification, can I do that?

**Comment by bowbowbow** [comment]
Of course! @gmatesunny

**Comment by gmatesunny** [comment]
I have one question why did you choose 0.69 in decision_tree.cpp
    double getEstimatedError(double f, int N) {
        double z = 0.69;

**Comment by bowbowbow** [comment]
It is used to mean z as described in this document. http://www.cs.bc.edu/~alvarez/ML/statPruning.html
